# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

# To run the container applications, initiate a command prompt at root and run the following command:
# NOTE: make sure the https certs are generated before hand. Refer to docker files on steps to generate certs.
# docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d

version: '3.4'

services:
  yzportal-api:
    image: yzportal-api
    build:
      context: .
      dockerfile: Dockerfile.YZPortal.API
  yzportal-client:
    image: yzportal-client
    build:
      context: .
      dockerfile: Dockerfile.YZPortal.Client
    ports:
        - "5207:80"
        - "7195:443"
    depends_on: 
        yzportal-api:
            condition: service_started
    volumes:
      - ${USERPROFILE}/nginx/ssl.crt:/etc/nginx/ssl.crt
      - ${USERPROFILE}/nginx/ssl.key:/etc/nginx/ssl.key
  
