# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

# To run the container applications, initiate a command prompt at root and run the following command:
# NOTE: make sure the https certs are generated before hand. Refer to docker files on steps to generate certs.
# docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d

version: '3.4'

services:
    yzportalapi:
        image: yzportalapi
        build:
            context: .
            dockerfile: Dockerfile.YZPortal.API
    yzportalclient:
        image: yzportalclient
        build:
            context: .
            dockerfile: Dockerfile.YZPortal.Client
        depends_on: 
            yzportalapi:
                condition: service_started
        
  
