name: 'Deploy Azure AD B2C custom policy'
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
env:
  clientId: 00250439-7907-492d-aa94-f040ba57171e
  tenant: yzorganization.onmicrosoft.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Upload TrustFrameworkBase Policy'
      uses: azure-ad-b2c/deploy-trustframework-policy@v5
      with:
        # The folder where the custom policies files are stored
        folder: "./Source/Web/YZPortal.API/Policies/AzureAdB2C"
        # Comma delimiter list of policy files
        files: "TrustFrameworkBase.xml,TrustFrameworkLocalization.xml,TrustFrameworkExtensions.xml,AccountLinkExtensions.xml,SignUpOrSignin.xml,AccountLinkSignUpOrSignin.xml,ProfileEdit.xml,PasswordReset.xml"
        # The full Azure AD B2C tenant name (for example, contoso.onmicrosoft.com) or GUID
        tenant: ${{ env.tenant }}
        # The application Client ID for a service principal which will be used to authenticate to the Microsoft Graph
        clientId: ${{ env.clientId }}
        # The application Secret for a service principal which will be used to authenticate to the Microsoft Graph
        clientSecret: ${{ secrets.AZUREADB2C_MANAGER_CLIENT_SECRET }}