name: 'deploy'
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: judedaryl/ieftool-action/setup@v1
      - uses: judedaryl/ieftool-action/build@v1
        with:
          source: src
          output: build
          config: ieftool.config
      - uses: judedaryl/ieftool-action/deploy@v1
        with:
          folder: build
          client-id: ${{ secrets.B2C_MANAGER_CLIENT_ID }}
          client-secret: ${{ secrets.B2C_MANAGER_CLIENT_SECRET }}
          tenant-id: ${{ secrets.B2C_TENANT_ID }}
