# REF: https://github.com/docker/build-push-action

name: Build and Push Docker Image

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push yzportal-api
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/yzportal-api:latest
                    file: Dockerfile.YZPortal.API
            -
                name: Build and push yzportal-client
                # REF: https://github.com/docker/build-push-action?tab=readme-ov-file
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/yzportal-client:latest
                    file: Dockerfile.YZPortal.Client