name: Deployment for yzportalapi Azure Container App

# When this action will be executed
on:
    # Automatically trigger it when detected changes in repo
    # push:
    #     branches: 
    #         [ master ]
    #     paths:
    #     - '**'
    #     - '.github/workflows/yzportalapi-AutoDeployTrigger-cf186ae9-4c16-47cd-829c-9b1a811d2427.yml'
    # Allow manual trigger 
    workflow_dispatch:      

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions: 
            id-token: write #This is required for requesting the OIDC JWT Token
            contents: read #Required when GH token is used to authenticate with private repo

        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push yzportalapi
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/yzportalapi:latest
                    file: Dockerfile.YZPortal.API
            - 
                name: Azure Login
                uses: azure/login@v1
                with:
                    client-id: ${{ secrets.YZPORTALAPI_AZURE_CLIENT_ID }}
                    tenant-id: ${{ secrets.YZPORTALAPI_AZURE_TENANT_ID }}
                    subscription-id: ${{ secrets.YZPORTALAPI_AZURE_SUBSCRIPTION_ID }}
            - 
                name: Build and push container image to registry
                uses: azure/container-apps-deploy-action@v2
                with:
                    appSourcePath: ${{ github.workspace }} 
                    registryUrl: dockerio
                    registryUsername: ${{ secrets.YZPORTALAPI_REGISTRY_USERNAME }}
                    registryPassword: ${{ secrets.YZPORTALAPI_REGISTRY_PASSWORD }}
                    containerAppName: yzportalapi
                    resourceGroup: YZPortal
                    imageToBuild: chinyizhe97/yzportalapi:${{ github.sha }}
                    _buildArgumentsKey_: |
                        _buildArgumentsValues_


